dhis2/d2-analysis

src/manager/AppManager.js
src/manager/InstanceManager.js
src/manager/UiManager.js
src/ui/EastRegion.js
src/ui/Viewport.js

- Interpretations are sorted by lastUpdated
- When interpretation id is found in the url, the interpretation is loaded on init. The infrastructure was already there but there was a couple of bugs parsing and validating the url attribute.
- Allows scroll bar for right side panel
- When interpretation is loaded by url, right side panel is expanded and left side panel collapsed.
- When an interpretation is loaded, either by url or selecting one of them on the right side panel, the rest of them are hidden on the east panel.

Interpretations improvements

---

src/manager/TableManager.js
src/table/PivotTable.js

Bug occurs when period selected as filter and user tries to use drill down functionality.

Fix for period drill down

---

src/table/PivotTable.js

fixed DHIS2-2205 for v28

---

src/api/Layout.js
src/ui/FavoriteButton.js
src/ui/NorthRegion.js
src/ui/PluginItem.js

@janhenrikoverland it seems PATCH works just fine.
The PR has also a couple of other fixes for using both name and displayName around.
This should add the fix to all the analytics apps.

Fix DHIS2-2784: preserve translations when saving

---

src/api/Layout.js
src/ui/EastRegion.js

Add subscription button to the East Region.
Requires: https://github.com/dhis2/dhis2-core/pull/1881

Add subscription icon to east region

---

src/index.js
src/ui/MentionToolbar.js

https://jira.dhis2.org/browse/DHIS2-3422
Fixes https://github.com/dhis2/charts-app/pull/39#issuecomment-393839432

Don't load ckeditor in the main module

---

src/ui/InterpretationWindow.js

https://jira.dhis2.org/browse/DHIS2-4265

Close mentions window when parent interpretation window is closed

---

src/api/Layout.js
src/manager/InstanceManager.js
src/ui/EastRegion.js

Fix/use favorite access object instead of PATCH request (v29)

---

src/api/Layout.js
src/manager/InstanceManager.js
src/ui/EastRegion.js

Same than #79, but for v29, apply after #77

Add extra checks for favorite and interpretation access (v29)

---

src/ui/EastRegion.js
src/util/dateUtils.js

Closes https://jira.dhis2.org/browse/DHIS2-5469
* `dateUtils.formatDate()` logic taken from dashboard-app.

Update interpretation and comment views to dashboard design (master)

---

src/ui/EastRegion.js
src/util/dateUtils.js

Closes https://jira.dhis2.org/browse/DHIS2-5469
* `dateUtils.formatDate()` logic taken from dashboard-app.

Update interpretation and comment views to dashboard design (v30)

---

package.json
src/ui/EastRegion.js
src/ui/FavoriteTextCmp.js
src/ui/InterpretationWindow.js
src/util/dom.js
yarn.lock

d2-ui-rich-text for favorite description, interpretations and comments

---

src/ui/MentionToolbar.js

Show a maximum of 5 entries on mentions user search

---

src/ui/MentionToolbar.js

Show a maximum of 5 entries on mentions user search (v30)

---

src/ui/MentionToolbar.js

Show a maximum of 5 entries on mentions user search (v31)

---

src/ui/EastRegion.js

Fixes https://jira.dhis2.org/browse/DHIS2-5472

Sort interpretations created desc

---

src/manager/AppManager.js
src/ui/WestRegionTrackerItems.js

fix: Load programs on app start to properly select program for opened AO [v32]

---

src/manager/AppManager.js
src/ui/WestRegionTrackerItems.js

fix: Load programs on app start to properly select program for opened AO [v31]

---

src/table/EventDataTable.js

Relates to [DHIS2-2480](https://jira.dhis2.org/browse/DHIS2-2480).

feat: Add enrollmentdate & incidentdate headers for events.

---

src/manager/AppManager.js
src/table/EventDataTable.js
src/ui/WestRegionTrackerItems.js

Relates to [DHIS2-2757](https://jira.dhis2.org/browse/DHIS2-2757).
Changes include:
- Enabling labels for incident/enrollment dates in ER events mode.

feat: Show labels for incident & enrollment dates

---

src/ui/WestRegionTrackerItems.js

Fixes [DHIS2-6868](https://jira.dhis2.org/browse/DHIS2-6868).
Changes include:
- Support for multiple filters for data elements with date/datetime value type.

fix: Enable multiple filters support for date/datetime value types in ER

---

src/ui/WestRegionTrackerItems.js

Relates to [DHIS2-6868](https://jira.dhis2.org/browse/DHIS2-6868).
Changes include:
- Fix for parsing multiple data element filters.

fix: Parsing multiple data element filters

---

src/ui/WestRegionTrackerItems.js

Fixes [DHIS2-6868](https://jira.dhis2.org/browse/DHIS2-6868).
Changes include:
- Accessing analytical object's `dataElementDimensions` property for `legendSet` object
- Assigning `legendSet` property to selected data element

fix: populating data element filter with values on app load 

---

src/ui/WestRegionTrackerItems.js

fix: Saving multiple data element filters v31

---

src/ui/WestRegionTrackerItems.js

fix: Saving multiple data element filters v32

---

src/ui/WestRegionTrackerItems.js

fix: Saving multiple data element filters v30

---

src/api/Layout.js

With this we can use Layout in DV plugin without having to provide
jQuery.

refactor: allow to use Layout without jQuery

---

src/config/DimensionConfig.js

fix: add 'AGE' as date type

---

src/ui/WestRegionTrackerItems.js

Fix for restoring program attributes and indicators correctly.

fix: restore program attributes/indicators correctly

---

src/ui/WestRegionTrackerItems.js

Restore category option group sets.

fix: restore cogs

---

src/ui/WestRegionTrackerItems.js

Restore multistage data elements. Respect type filter. Hide already selected elements.

fix: restore multistage data elements

---

src/ui/WestRegionTrackerItems.js

Fixes https://jira.dhis2.org/browse/DHIS2-10163 by passing down the already fetched program containing metadata about program attributes and program indicators.

fix: get program attribute and indicator metadata from program (DHIS2-10163)

---

src/ui/WestRegionAggregateItems.js
src/ui/WestRegionTrackerItems.js

Respects the default relative period system setting.

fix: default relative period

---

src/util/Plugin.js

NB: Work in progress.
Adds a public function that reloads the currently loaded visualizations.

feat: add reload fn

---

src/ui/WestRegionTrackerItems.js

Closes https://jira.dhis2.org/browse/DHIS2-7353

fix: html escape program names

---

src/ui/WestRegionTrackerItems.js

Get stage from layout and set on items.

fix: get program stage from layout

---

src/ui/Viewport.js
src/ux/StatusBar.js

Description: https://jira.dhis2.org/browse/DHIS2-13092

fix: paging issues (DHIS2-13092)

---

src/config/DimensionConfig.js
src/ui/WestRegionTrackerItems.js
src/ux/DataElementStringContainer.js

Fixes [DHIS2-15816](https://dhis2.atlassian.net/browse/DHIS2-15816)
[DHIS2-15816]: https://dhis2.atlassian.net/browse/DHIS2-15816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: apply filter when restoring data items (DHIS2-15816)

---

src/init/userFavoritesInit.js
src/manager/AppManager.js
src/ui/EastRegion.js
src/ui/MentionToolbar.js
src/util/Plugin.js

Fixes https://dhis2.atlassian.net/browse/DHIS2-17631

fix: migrate away from deprecated userCredentials object (DHIS2-17631)

---

src/ui/WestRegionTrackerItems.js

If the data item is not a data element, the stage id should not be in the request.

fix: do not request stage for attrs and program indicators
